# Generated by Django 3.1.6 on 2021-02-18 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Oleo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='nome')),
                ('intervalo_de_troca_km', models.IntegerField(verbose_name='intervalo_de_troca_km')),
            ],
        ),
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='placa')),
            ],
        ),
        migrations.CreateModel(
            name='ServicoEfetuado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(verbose_name='data')),
                ('valor', models.FloatField(verbose_name='valor')),
                ('servico_idservico', models.IntegerField(verbose_name='servico_idservico')),
                ('veiculo_idveiculo', models.IntegerField(verbose_name='veiculo_idveiculo')),
            ],
        ),
    ]
