# Generated by Django 3.1.6 on 2021-02-19 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20210219_1030'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servico',
            name='nome',
        ),
        migrations.AddField(
            model_name='servico',
            name='descricao',
            field=models.CharField(default=0, max_length=250, unique=True, verbose_name='descricao'),
            preserve_default=False,
        ),
    ]
