# Generated by Django 3.1.6 on 2021-02-19 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20210219_1055'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrocaDeOleo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(verbose_name='data')),
                ('valor', models.FloatField(blank=True, verbose_name='valor')),
                ('oleo_idoleo', models.IntegerField(verbose_name='oleo_idoleo')),
                ('veiculo_idveiculo', models.IntegerField(verbose_name='veiculo_idveiculo')),
                ('km_odometro', models.IntegerField(verbose_name='km_odometro')),
            ],
        ),
    ]
